import React from "react";
import { workspaceMetrics, latestReviews, downloadReview } from "../utils/securityWorkspace";

export default function SecurityOverview({ workspace, onConnect, onOpenProject, onOpenFindings }) {
  if (workspace.pending) return <section className="saas-panel"><p className="saas-muted">Loading saved repositories and review records…</p></section>;
  const metrics = workspaceMetrics(workspace.projects, workspace.reviews, workspace.decisions);
  const recent = [...workspace.reviews].sort((a, b) => b.createdAt.localeCompare(a.createdAt)).slice(0, 4);
  return <div className="security-overview">
    <div className="security-page-title"><div><p className="security-kicker">REPOSITORY SECURITY</p><h1>Your review workspace</h1><p>Source evidence, review decisions, and a record of what changed.</p></div><button className="saas-primary" onClick={onConnect}>Connect repository</button></div>
    <div className="security-metrics">{[["Repositories", metrics.projects], ["Saved reviews", metrics.reviews], ["Open findings", metrics.open], ["High / critical open", metrics.high]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong><small>{label.includes("open") || label === "Open findings" ? "From the latest review per repository" : "Saved in this workspace"}</small></div>)}</div>
    <div className="security-columns"><section className="saas-panel"><div className="saas-section-title"><h2>Repositories</h2><span>{workspace.cloud ? "Account workspace" : "Local workspace"}</span></div>
      {workspace.projects.length ? workspace.projects.map((project) => { const latest = latestReviews(workspace.reviews).find((review) => review.projectId === project.id);
        return <button className="saas-project-row" key={project.id} onClick={() => onOpenProject(project.id)}><span><strong>{project.fullName}</strong><small>{project.fileCount.toLocaleString()} text files discovered · {latest ? `Last reviewed ${new Date(latest.createdAt).toLocaleDateString()}` : "Awaiting first review"}</small></span><span>{latest ? `${latest.report.findings.length} indicators` : "Open project"}</span></button>;
      }) : <div className="saas-empty"><h3>Start with a repository</h3><p>Connect GitHub, review a fixed source revision, then track each finding through a decision.</p><button className="saas-secondary" onClick={onConnect}>Connect your first repository</button></div>}
    </section><section className="saas-panel"><div className="saas-section-title"><h2>Review queue</h2><button onClick={onOpenFindings}>Open inbox</button></div><p className="saas-queue-count">{metrics.open}<span>findings to review</span></p><p className="saas-muted">Only findings from each repository’s latest saved review appear in the queue. Older results remain in review history.</p><div className="saas-process"><span>01 · Connect a repository</span><span>02 · Review source evidence</span><span>03 · Record a decision & export</span></div></section></div>
    <section className="saas-panel"><div className="saas-section-title"><h2>Recent reviews</h2><span>Commit-linked records</span></div>{recent.length ? recent.map((review) => <div className="saas-review-row" key={review.id}><span><strong>{review.report.repository}</strong><small>{review.report.revision.slice(0, 12)} · {new Date(review.createdAt).toLocaleString()} · {review.report.model}</small></span><span>{review.report.analyzed_files.length}/{review.report.eligible_files} eligible files</span><button className="saas-secondary" onClick={() => downloadReview(review, workspace.decisions)}>Export report</button></div>) : <p className="saas-muted">No saved security reviews yet. A Gemini key is required to run a real review; demo tool output is never added here.</p>}</section>
    <p className="saas-footnote">{workspace.cloud ? "Owner-scoped Firebase records." : "Projects and reviews are saved on this device. Sign in with Google to sync them to your account."} Static source review; indicators require human assessment.</p>
  </div>;
}
